dict = {0: {'aka': ['LTC'], 'name': 'Litecoin'},
 1: {'aka': ['DOGE'], 'name': 'Dogecoin'},
 2: {'aka': ['VTC'], 'name': 'Vertcoin'},
 3: {'aka': ['PPC'], 'name': 'Peercoin'},
 4: {'aka': ['FTC'], 'name': 'Feathercoin'},
 5: {'aka': ['RDD'], 'name': 'ReddCoin'},
 6: {'aka': ['NXT'], 'name': 'NXT'},
 7: {'aka': ['DASH'], 'name': 'Dash'},
 8: {'aka': ['POT'], 'name': 'PotCoin'},
 9: {'aka': ['BLK'], 'name': 'BlackCoin'},
 10: {'aka': ['EMC2'], 'name': 'Einsteinium'},
 11: {'aka': ['XMY'], 'name': 'Myriad'},
 12: {'aka': ['AUR'], 'name': 'AuroraCoin'},
 13: {'aka': ['EFL'], 'name': 'ElectronicGulden'},
 14: {'aka': ['GLD'], 'name': 'GoldCoin'},
 15: {'aka': ['SLR'], 'name': 'SolarCoin'},
 16: {'aka': ['PTC'], 'name': 'PesetaCoin '},
 17: {'aka': ['GRS'], 'name': 'Groestlcoin'},
 18: {'aka': ['NLG'], 'name': 'Gulden'},
 19: {'aka': ['RBY'], 'name': 'RubyCoin'},
 20: {'aka': ['XWC'], 'name': 'WhiteCoin'},
 21: {'aka': ['MONA'], 'name': 'MonaCoin'},
 22: {'aka': ['THC'], 'name': 'HempCoin'},
 23: {'aka': ['ENRG'], 'name': 'EnergyCoin'},
 24: {'aka': ['ERC'], 'name': 'EuropeCoin'},
 25: {'aka': ['VRC'], 'name': 'VeriCoin'},
 26: {'aka': ['CURE'], 'name': 'CureCoin'},
 27: {'aka': ['XMR'], 'name': 'Monero'},
 28: {'aka': ['CLOAK'], 'name': 'CloakCoin'},
 29: {'aka': ['START'], 'name': 'StartCoin'},
 30: {'aka': ['KORE'], 'name': 'KoreCoin'},
 31: {'aka': ['XDN'], 'name': 'DigitalNote'},
 32: {'aka': ['TRUST'], 'name': 'TrustPlus'},
 33: {'aka': ['NAV'], 'name': 'NAVCoin'},
 34: {'aka': ['XST'], 'name': 'StealthCoin'},
 35: {'aka': ['BTCD'], 'name': 'BitcoinDark'},
 36: {'aka': ['VIA'], 'name': 'ViaCoin '},
 37: {'aka': ['UNO'], 'name': 'Unobtanium'},
 38: {'aka': ['PINK'], 'name': 'PinkCoin'},
 39: {'aka': ['IOC'], 'name': 'IOCoin'},
 40: {'aka': ['CANN'], 'name': 'CannabisCoin'},
 41: {'aka': ['SYS'], 'name': 'SysCoin'},
 42: {'aka': ['NEOS'], 'name': 'NeosCoin'},
 43: {'aka': ['DGB'], 'name': 'Digibyte'},
 44: {'aka': ['BURST'], 'name': 'BURSTCoin'},
 45: {'aka': ['EXCL'], 'name': 'ExclusiveCoin'},
 46: {'aka': ['SWIFT'], 'name': 'Bitswift'},
 47: {'aka': ['DOPE'], 'name': 'DopeCoin'},
 48: {'aka': ['BLOCK'], 'name': 'BlockNet'},
 49: {'aka': ['ABY'], 'name': 'ArtByte'},
 50: {'aka': ['BYC'], 'name': 'Bytecent'},
 51: {'aka': ['XMG'], 'name': 'Magi'},
 52: {'aka': ['BLITZ'], 'name': 'Blitzcash'},
 53: {'aka': ['BAY'], 'name': 'BitBay'},
 54: {'aka': ['BTS'], 'name': 'BitShares'},
 55: {'aka': ['FAIR'], 'name': 'FairCoin'},
 56: {'aka': ['SPR'], 'name': 'SpreadCoin'},
 57: {'aka': ['VTR'], 'name': 'vTorrent'},
 58: {'aka': ['XRP'], 'name': 'Ripple'},
 59: {'aka': ['GAME'], 'name': 'GameCredits'},
 60: {'aka': ['COVAL'], 'name': 'Circuits of Value'},
 61: {'aka': ['NXS'], 'name': 'Nexus'},
 62: {'aka': ['XCP'], 'name': 'Counterparty'},
 63: {'aka': ['BITB'], 'name': 'BitBean'},
 64: {'aka': ['GEO'], 'name': 'GeoCoin'},
 65: {'aka': ['FLDC'], 'name': 'FoldingCoin'},
 66: {'aka': ['GRC'], 'name': 'GridCoin'},
 67: {'aka': ['FLO'], 'name': 'Florin'},
 68: {'aka': ['NBT'], 'name': 'Nubits'},
 69: {'aka': ['MUE'], 'name': 'MonetaryUnit'},
 70: {'aka': ['XEM'], 'name': 'NewEconomyMovement'},
 71: {'aka': ['CLAM'], 'name': 'CLAMs'},
 72: {'aka': ['DMD'], 'name': 'Diamond'},
 73: {'aka': ['GAM'], 'name': 'Gambit'},
 74: {'aka': ['SPHR'], 'name': 'Sphere'},
 75: {'aka': ['OK'], 'name': 'OkCash'},
 76: {'aka': ['SNRG'], 'name': 'Synergy'},
 77: {'aka': ['PKB'], 'name': 'ParkByte'},
 78: {'aka': ['CPC'], 'name': 'CapriCoin'},
 79: {'aka': ['AEON'], 'name': 'Aeon'},
 80: {'aka': ['ETH'], 'name': 'Ethereum'},
 81: {'aka': ['GCR'], 'name': 'GlobalCurrencyReserve'},
 82: {'aka': ['TX'], 'name': 'TransferCoin'},
 83: {'aka': ['BCY'], 'name': 'BitCrystals'},
 84: {'aka': ['EXP'], 'name': 'Expanse'},
 85: {'aka': ['INFX'], 'name': 'InfluxCoin'},
 86: {'aka': ['OMNI'], 'name': 'OMNI'},
 87: {'aka': ['AMP'], 'name': 'AMP'},
 88: {'aka': ['AGRS'], 'name': 'IDNI Agoras'},
 89: {'aka': ['XLM'], 'name': 'Lumen'},
 90: {'aka': ['BTA'], 'name': 'Bata'},
 92: {'aka': ['CLUB'], 'name': 'ClubCoin'},
 93: {'aka': ['VOX'], 'name': 'Voxels'},
 94: {'aka': ['EMC'], 'name': 'EmerCoin'},
 95: {'aka': ['FCT'], 'name': 'Factom'},
 96: {'aka': ['MAID'], 'name': 'MaidSafe'},
 97: {'aka': ['EGC'], 'name': 'EverGreenCoin'},
 98: {'aka': ['SLS'], 'name': 'SaluS'},
 99: {'aka': ['RADS'], 'name': 'Radium'},
 100: {'aka': ['DCR'], 'name': 'Decred'},
 101: {'aka': ['SAFEX'], 'name': 'SafeExchangeCoin'},
 102: {'aka': ['BSD'], 'name': 'BitSend'},
 103: {'aka': ['XVG'], 'name': 'Verge'},
 104: {'aka': ['PIVX'], 'name': 'Pivx'},
 105: {'aka': ['XVC'], 'name': 'Vcash'},
 106: {'aka': ['MEME'], 'name': 'Memetic'},
 107: {'aka': ['STEEM'], 'name': 'STEEM'},
 109: {'aka': ['LSK'], 'name': 'Lisk'},
 110: {'aka': ['PDC'], 'name': 'Project Decorum'},
 111: {'aka': ['BRK'], 'name': 'Breakout'},
 112: {'aka': ['DGD'], 'name': 'DigixDAO'},
 114: {'aka': ['WAVES'], 'name': 'Waves'},
 115: {'aka': ['RISE'], 'name': 'Rise'},
 116: {'aka': ['LBC'], 'name': 'LBRY Credits'},
 117: {'aka': ['SBD'], 'name': 'SteemDollars'},
 118: {'aka': ['BRX'], 'name': 'Breakout Stake'},
 119: {'aka': ['DRACO'], 'name': 'DT Token'},
 120: {'aka': ['ETC'], 'name': 'Ethereum Classic'},
 122: {'aka': ['STRAT'], 'name': 'Stratis'},
 123: {'aka': ['UNB'], 'name': 'UnbreakableCoin'},
 124: {'aka': ['SYNX'], 'name': 'Syndicate'},
 125: {'aka': ['TRIG'], 'name': 'TRIG Token'},
 126: {'aka': ['EBST'], 'name': 'eBoost'},
 127: {'aka': ['VRM'], 'name': 'Verium'},
 128: {'aka': ['SEQ'], 'name': 'Sequence'},
 129: {'aka': ['XAUR'], 'name': 'Xaurum'},
 130: {'aka': ['SNGLS'], 'name': 'SingularDTV'},
 131: {'aka': ['REP'], 'name': 'Augur'},
 132: {'aka': ['SHIFT'], 'name': 'Shift'},
 133: {'aka': ['ARDR'], 'name': 'Ardor'},
 134: {'aka': ['XZC'], 'name': 'ZCoin'},
 135: {'aka': ['NEO'], 'name': 'Neo'},
 136: {'aka': ['ZEC'], 'name': 'Zcash'},
 137: {'aka': ['ZCL'], 'name': 'Zclassic'},
 138: {'aka': ['IOP'], 'name': 'Internet Of People'},
 139: {'aka': ['DAR'], 'name': 'Darcrus'},
 140: {'aka': ['GOLOS'], 'name': 'Golos'},
 141: {'aka': ['UBQ'], 'name': 'Ubiq'},
 142: {'aka': ['KMD'], 'name': 'Komodo'},
 143: {'aka': ['GBG'], 'name': 'GBG'},
 144: {'aka': ['SIB'], 'name': 'Siberian Chervonets'},
 145: {'aka': ['ION'], 'name': 'Ion'},
 146: {'aka': ['LMC'], 'name': 'Lomocoin'},
 147: {'aka': ['QWARK'], 'name': 'Qwark'},
 148: {'aka': ['CRW'], 'name': 'Crown'},
 149: {'aka': ['SWT'], 'name': 'Swarm City Token'},
 150: {'aka': ['TIME'], 'name': 'Chronobank Time'},
 151: {'aka': ['MLN'], 'name': 'Melon'},
 152: {'aka': ['ARK'], 'name': 'Ark'},
 153: {'aka': ['DYN'], 'name': 'Dynamic'},
 154: {'aka': ['TKS'], 'name': 'Tokes'},
 155: {'aka': ['MUSIC'], 'name': 'Musicoin'},
 156: {'aka': ['DTB'], 'name': 'Databits'},
 157: {'aka': ['INCNT'], 'name': 'Incent'},
 158: {'aka': ['GBYTE'], 'name': 'Bytes'},
 159: {'aka': ['GNT'], 'name': 'Golem'},
 160: {'aka': ['NXC'], 'name': 'Nexium'},
 161: {'aka': ['EDG'], 'name': 'Edgeless'},
 162: {'aka': ['LGD'], 'name': 'Legends'},
 163: {'aka': ['TRST'], 'name': 'Trustcoin'},
 168: {'aka': ['WINGS'], 'name': 'Wings DAO'},
 169: {'aka': ['RLC'], 'name': 'iEx.ec'},
 170: {'aka': ['GNO'], 'name': 'Gnosis'},
 171: {'aka': ['GUP'], 'name': 'Guppy'},
 172: {'aka': ['LUN'], 'name': 'Lunyr'},
 178: {'aka': ['APX'], 'name': 'Apx'},
 179: {'aka': ['TKN'], 'name': 'TokenCard'},
 181: {'aka': ['HMQ'], 'name': 'Humaniq'},
 183: {'aka': ['ANT'], 'name': 'Aragon'},
 186: {'aka': ['SC'], 'name': 'Siacoin'},
 188: {'aka': ['BAT'], 'name': 'Basic Attention Token'},
 189: {'aka': ['ZEN'], 'name': 'Zencash'},
 190: {'aka': ['1ST'], 'name': 'FirstBlood'},
 191: {'aka': ['QRL'], 'name': 'Quantum Resistant Ledger'},
 194: {'aka': ['CRB'], 'name': 'CreditBit'},
 197: {'aka': ['PTOY'], 'name': 'Patientory'},
 199: {'aka': ['MYST'], 'name': 'Mysterium'},
 201: {'aka': ['CFI'], 'name': 'Cofound.it'},
 203: {'aka': ['BNT'], 'name': 'Bancor'},
 205: {'aka': ['NMR'], 'name': 'Numeraire'},
 210: {'aka': ['SNT'], 'name': 'Status Network Token'},
 212: {'aka': ['DCT'], 'name': 'DECENT'},
 213: {'aka': ['XEL'], 'name': 'Elastic'},
 214: {'aka': ['MCO'], 'name': 'Monaco'},
 216: {'aka': ['ADT'], 'name': 'adToken'},
 218: {'aka': ['FUN'], 'name': 'FunFair'},
 220: {'aka': ['PAY'], 'name': 'TenX Pay Token'},
 222: {'aka': ['MTL'], 'name': 'Metal'},
 224: {'aka': ['STORJ'], 'name': 'Storj'},
 226: {'aka': ['ADX'], 'name': 'AdEx'},
 235: {'aka': ['OMG'], 'name': 'OmiseGO'},
 237: {'aka': ['CVC'], 'name': 'Civic'},
 239: {'aka': ['PART'], 'name': 'Particl'},
 240: {'aka': ['QTUM'], 'name': 'Qtum'},
 250: {'aka': ['BCC'], 'name': 'Bitcoin Cash'}}
